{
  "timestamp": "2025-07-20T11:11:34.342183",
  "version": "CHNeoWave v1.1.0-beta",
  "total_tests": 3,
  "passed": 0,
  "failed": 3,
  "errors": 0,
  "timeouts": 0,
  "total_duration": 13.19908356666565,
  "results": {
    "test_launch_gui.py": {
      "status": "failed",
      "duration": 5.393625736236572,
      "output": "============================= test session starts =============================\ncollecting ... collected 3 items\n\ntests_smoke/test_launch_gui.py::TestLaunchGUI::test_gui_startup_simulation ",
      "error": ""
    },
    "test_export_hdf5.py": {
      "status": "failed",
      "duration": 1.8572149276733398,
      "output": "============================= test session starts =============================\ncollecting ... collected 4 items\n\ntests_smoke/test_export_hdf5.py::TestExportHDF5::test_hdf5_writer_basic FAILED [ 25%]\ntests_smoke/test_export_hdf5.py::TestExportHDF5::test_simulated_acquisition_export FAILED [ 50%]\ntests_smoke/test_export_hdf5.py::TestExportHDF5::test_hdf5_integrity_verification FAILED [ 75%]\ntests_smoke/test_export_hdf5.py::TestExportHDF5::test_large_dataset_export FAILED [100%]\n\n================================== FAILURES ===================================\n____________________ TestExportHDF5.test_hdf5_writer_basic ____________________\ntests_smoke\\test_export_hdf5.py:69: in test_hdf5_writer_basic\n    file_hash = writer.write_acquisition_data(\nsrc\\hrneowave\\utils\\hdf_writer.py:94: in write_acquisition_data\n    raw_dataset.attrs['sha256'] = file_hash.encode('utf-8')\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^\nh5py/_objects.pyx:56: in h5py._objects.with_phil.wrapper\n    ???\nh5py/_objects.pyx:57: in h5py._objects.with_phil.wrapper\n    ???\nvenv\\Lib\\site-packages\\h5py\\_hl\\attrs.py:104: in __setitem__\n    self.create(name, data=value)\nvenv\\Lib\\site-packages\\h5py\\_hl\\attrs.py:199: in create\n    if h5a.exists(self._id, name):\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^\nh5py/_objects.pyx:56: in h5py._objects.with_phil.wrapper\n    ???\nh5py/_objects.pyx:57: in h5py._objects.with_phil.wrapper\n    ???\nh5py/h5a.pyx:103: in h5py.h5a.exists\n    ???\nE   RuntimeError: Can't synchronously determine if attribute exists by name (invalid identifier type to function)\n\nDuring handling of the above exception, another exception occurred:\ntests_smoke\\test_export_hdf5.py:95: in test_hdf5_writer_basic\n    pytest.fail(f\"Erreur test HDF5Writer basique: {str(e)}\")\nE   Failed: Erreur test HDF5Writer basique: Can't synchronously determine if attribute exists by name (invalid identifier type to function)\n---------------------------- Captured stdout setup ----------------------------\n\\n=== Configuration environnement de test CHNeoWave ===\\nR\\xe9pertoire projet: C:\\\\Users\\\\LEM\\\\Desktop\\\\chneowave\\nR\\xe9pertoire source: C:\\\\Users\\\\LEM\\\\Desktop\\\\chneowave\\\\src\\nPython: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]\\n\\u2713 PyQt5\\n\\u2713 numpy\\n\\u2713 scipy\\n\\u2713 h5py\\n\\u2713 reportlab\\n\\u2713 pyqtgraph\\n=== Environnement de test pr\\xeat ===\n______________ TestExportHDF5.test_simulated_acquisition_export _______________\ntests_smoke\\test_export_hdf5.py:126: in test_simulated_acquisition_export\n    if backend.has_data():\n       ^^^^^^^^^^^^^^^^\nE   AttributeError: 'DemoBackend' object has no attribute 'has_data'\n\nDuring handling of the above exception, another exception occurred:\ntests_smoke\\test_export_hdf5.py:187: in test_simulated_acquisition_export\n    pytest.fail(f\"Erreur acquisition/export HDF5: {str(e)}\")\nE   Failed: Erreur acquisition/export HDF5: 'DemoBackend' object has no attribute 'has_data'\n---------------------------- Captured stdout call -----------------------------\nDémarrage acquisition simulée: 5.0s à 32Hz, 8 canaux\n------------------------------ Captured log call ------------------------------\nERROR    hrneowave.hw.demo_backend:demo_backend.py:101 Callback de données non défini\n_______________ TestExportHDF5.test_hdf5_integrity_verification _______________\ntests_smoke\\test_export_hdf5.py:208: in test_hdf5_integrity_verification\n    file_hash = writer.write_acquisition_data(\nsrc\\hrneowave\\utils\\hdf_writer.py:94: in write_acquisition_data\n    raw_dataset.attrs['sha256'] = file_hash.encode('utf-8')\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^\nh5py/_objects.pyx:56: in h5py._objects.with_phil.wrapper\n    ???\nh5py/_objects.pyx:57: in h5py._objects.with_phil.wrapper\n    ???\nvenv\\Lib\\site-packages\\h5py\\_hl\\attrs.py:104: in __setitem__\n    self.create(name, data=value)\nvenv\\Lib\\site-packages\\h5py\\_hl\\attrs.py:199: in create\n    if h5a.exists(self._id, name):\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^\nh5py/_objects.pyx:56: in h5py._objects.with_phil.wrapper\n    ???\nh5py/_objects.pyx:57: in h5py._objects.with_phil.wrapper\n    ???\nh5py/h5a.pyx:103: in h5py.h5a.exists\n    ???\nE   RuntimeError: Can't synchronously determine if attribute exists by name (invalid identifier type to function)\n\nDuring handling of the above exception, another exception occurred:\ntests_smoke\\test_export_hdf5.py:238: in test_hdf5_integrity_verification\n    pytest.fail(f\"Erreur test intégrité HDF5: {str(e)}\")\nE   Failed: Erreur test intégrité HDF5: Can't synchronously determine if attribute exists by name (invalid identifier type to function)\n__________________ TestExportHDF5.test_large_dataset_export ___________________\ntests_smoke\\test_export_hdf5.py:265: in test_large_dataset_export\n    file_hash = writer.write_acquisition_data(\nsrc\\hrneowave\\utils\\hdf_writer.py:94: in write_acquisition_data\n    raw_dataset.attrs['sha256'] = file_hash.encode('utf-8')\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^\nh5py/_objects.pyx:56: in h5py._objects.with_phil.wrapper\n    ???\nh5py/_objects.pyx:57: in h5py._objects.with_phil.wrapper\n    ???\nvenv\\Lib\\site-packages\\h5py\\_hl\\attrs.py:104: in __setitem__\n    self.create(name, data=value)\nvenv\\Lib\\site-packages\\h5py\\_hl\\attrs.py:199: in create\n    if h5a.exists(self._id, name):\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^\nh5py/_objects.pyx:56: in h5py._objects.with_phil.wrapper\n    ???\nh5py/_objects.pyx:57: in h5py._objects.with_phil.wrapper\n    ???\nh5py/h5a.pyx:103: in h5py.h5a.exists\n    ???\nE   RuntimeError: Can't synchronously determine if attribute exists by name (invalid identifier type to function)\n\nDuring handling of the above exception, another exception occurred:\ntests_smoke\\test_export_hdf5.py:300: in test_large_dataset_export\n    pytest.fail(f\"Erreur test large dataset: {str(e)}\")\nE   Failed: Erreur test large dataset: Can't synchronously determine if attribute exists by name (invalid identifier type to function)\n-------------------------- Captured stdout teardown ---------------------------\n\n=== Nettoyage environnement de test ===\n=========================== short test summary info ===========================\nFAILED tests_smoke/test_export_hdf5.py::TestExportHDF5::test_hdf5_writer_basic\nFAILED tests_smoke/test_export_hdf5.py::TestExportHDF5::test_simulated_acquisition_export\nFAILED tests_smoke/test_export_hdf5.py::TestExportHDF5::test_hdf5_integrity_verification\nFAILED tests_smoke/test_export_hdf5.py::TestExportHDF5::test_large_dataset_export\n============================== 4 failed in 1.16s ==============================\n",
      "error": ""
    },
    "test_calib_pdf.py": {
      "status": "failed",
      "duration": 5.948242902755737,
      "output": "============================= test session starts =============================\ncollecting ... collected 6 items\n\ntests_smoke/test_calib_pdf.py::TestCalibPDF::test_pdf_generator_basic PASSED [ 16%]\ntests_smoke/test_calib_pdf.py::TestCalibPDF::test_pdf_content_verification FAILED [ 33%]\ntests_smoke/test_calib_pdf.py::TestCalibPDF::test_pdf_with_high_quality_calibration PASSED [ 50%]\ntests_smoke/test_calib_pdf.py::TestCalibPDF::test_pdf_with_multiple_sensors PASSED [ 66%]\ntests_smoke/test_calib_pdf.py::TestCalibPDF::test_pdf_signature_verification FAILED [ 83%]\ntests_smoke/test_calib_pdf.py::TestCalibPDF::test_pdf_error_handling FAILED [100%]\n\n================================== FAILURES ===================================\n_________________ TestCalibPDF.test_pdf_content_verification __________________\ntests_smoke\\test_calib_pdf.py:116: in test_pdf_content_verification\n    assert 'CHNeoWave' in pdf_content, \"Titre CHNeoWave manquant\"\nE   AssertionError: Titre CHNeoWave manquant\nE   assert 'CHNeoWave' in '%PDF-1.4\\n%\\x93\\x8c\\x8b\\x9e ReportLab Generated PDF document http://www.reportlab.com\\n1 0 obj\\n<<\\n/F1 2 0 R /F2 3 0 R /F3 4 0 R\\n>>\\nendobj\\n2 0 obj\\n<<\\n/BaseFont /Helvetica /Encoding /WinAnsiEncoding /Name /F1 /Subtype /Type1 /Type /Font\\n>>\\nendobj\\n3 0 obj\\n<<\\n/BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding /Name /F2 /Subtype /Type1 /Type /Font\\n>>\\nendobj\\n4 0 obj\\n<<\\n/BaseFont /ZapfDingbats /Name /F3 /Subtype /Type1 /Type /Font\\n>>\\nendobj\\n5 0 obj\\n<<\\n/Contents 12 0 R /MediaBox [ 0 0 595.2756 841.8898 ] /Parent 11 0 R /Resources <<\\n/Font 1 0 R /ProcSet [ /PDF /Text /ImageB /ImageC /ImageI ]\\n>> /Rotate 0 /Trans <<\\n\\n>> \\n  /Type /Page\\n>>\\nendobj\\n6 0 obj\\n<<\\n/BitsPerComponent 8 /ColorSpace /DeviceRGB /Filter [ /ASCII85Decode /FlateDecode ] /Height 817 /Length 73363 /SMask 7 0 R \\n  /Subtype /Image /Type /XObject /Width 1029\\n>>\\nstream\\nGb\",k#C$q_pVqi-.n)bBNei.WT@2d6WDWn6+]S8qMI:?F.S<R;&l=Aq66Lq2T_\\'-h#`qgF&5).LOG*7th>*\\\\f`Q>>9]:8.^-Kk=jqrHGc\\\\U4)=H$<oI]5rlU!<<*\"zzzzzzzzzzzzzzzzzzzzzzzzP[9Y.>rmH4pm!@2Wnif3aihks3cuqF2DR$cmCiQ#zTQrG6hH[3g\\\\N4lu>e5#KmCj:ZW)9>Fgt^VkCR:6KUNTuEz!,rtI^ABNo_Xt;?gUqe$@Z;9`*dHUo6\\\\c/:@\\'aHZe#!TIJ,K*3%_&ZN_Zk-6N>aZH:/3F(/ib/PJjkS5;9M`u...dstream\\nendobj\\n13 0 obj\\n<<\\n/Filter [ /ASCII85Decode /FlateDecode ] /Length 535\\n>>\\nstream\\nGat=\\'95i<6&AI=/b],qKf/%kNDpVC.W%&r7d6fQ^m&Us[)]E;bqm\"C4]?jH/-F+h@4Q\"&K&S*MqCHhm5Dde\\'FJ->6>W.g!\"$9kiAI=m;MAjJs\\'Zq\"O5@m63&\\'jKXVe?t.c$*0R\\\\9Pr>sdlcJ\\\\S`h&]Y)CBPl)8.Rk`iPGpWdo)0F[,Co-r99RO)C115`N$E6gJAVgJV=`C(ii>B0q$ZK2>R9p6m_0@a4_Qk`QN=r$q/GP-6nfnF!%-b/#o\\\\\\'!XA^#,_Hd!g]BD6`+IP0uMPE!/Q4W7ZFh\"&9Uk=_ll)`63?PAF+$LW&INl<fl[`^\"1^1ThCEBn%pb,f1FenO^[/ZrP2s=dLcr]a9K8TU/FUIoC6tOb4C+Gr`H8T<I`-mGNhp&,hLJH8WnX/V=ReOc(C_[i+:HrD`g[?V1FXNU\"SU*J2!F\\':51LA)IH)>K!0a(i\\\\A1NT1A&22T\"`16(d:N4)Feu5_(&-W=E`nF!U+=BadX+c^8k`Hj_a#?!aGn96a\"sJ-(H&l,:[ub/\"p.^&nSudDu~>endstream\\nendobj\\nxref\\n0 14\\n0000000000 65535 f \\n0000000073 00000 n \\n0000000124 00000 n \\n0000000231 00000 n \\n0000000343 00000 n \\n0000000426 00000 n \\n0000000631 00000 n \\n0000074200 00000 n \\n0000074649 00000 n \\n0000074917 00000 n \\n0000074986 00000 n \\n0000075270 00000 n \\n0000075336 00000 n \\n0000076717 00000 n \\ntrailer\\n<<\\n/ID \\n[<a19b1cbf7a1c4370439b4e3841839780><a19b1cbf7a1c4370439b4e3841839780>]\\n% ReportLab generated PDF document -- digest (http://www.reportlab.com)\\n\\n/Info 10 0 R\\n/Root 9 0 R\\n/Size 14\\n>>\\nstartxref\\n77343\\n%%EOF\\n'\n\nDuring handling of the above exception, another exception occurred:\ntests_smoke\\test_calib_pdf.py:137: in test_pdf_content_verification\n    pytest.fail(f\"Erreur vérification contenu PDF: {str(e)}\")\nE   Failed: Erreur vérification contenu PDF: Titre CHNeoWave manquant\nE   assert 'CHNeoWave' in '%PDF-1.4\\n%\\x93\\x8c\\x8b\\x9e ReportLab Generated PDF document http://www.reportlab.com\\n1 0 obj\\n<<\\n/F1 2 0 R /F2 3 0 R /F3 4 0 R\\n>>\\nendobj\\n2 0 obj\\n<<\\n/BaseFont /Helvetica /Encoding /WinAnsiEncoding /Name /F1 /Subtype /Type1 /Type /Font\\n>>\\nendobj\\n3 0 obj\\n<<\\n/BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding /Name /F2 /Subtype /Type1 /Type /Font\\n>>\\nendobj\\n4 0 obj\\n<<\\n/BaseFont /ZapfDingbats /Name /F3 /Subtype /Type1 /Type /Font\\n>>\\nendobj\\n5 0 obj\\n<<\\n/Contents 12 0 R /MediaBox [ 0 0 595.2756 841.8898 ] /Parent 11 0 R /Resources <<\\n/Font 1 0 R /ProcSet [ /PDF /Text /ImageB /ImageC /ImageI ]\\n>> /Rotate 0 /Trans <<\\n\\n>> \\n  /Type /Page\\n>>\\nendobj\\n6 0 obj\\n<<\\n/BitsPerComponent 8 /ColorSpace /DeviceRGB /Filter [ /ASCII85Decode /FlateDecode ] /Height 817 /Length 73363 /SMask 7 0 R \\n  /Subtype /Image /Type /XObject /Width 1029\\n>>\\nstream\\nGb\",k#C$q_pVqi-.n)bBNei.WT@2d6WDWn6+]S8qMI:?F.S<R;&l=Aq66Lq2T_\\'-h#`qgF&5).LOG*7th>*\\\\f`Q>>9]:8.^-Kk=jqrHGc\\\\U4)=H$<oI]5rlU!<<*\"zzzzzzzzzzzzzzzzzzzzzzzzP[9Y.>rmH4pm!@2Wnif3aihks3cuqF2DR$cmCiQ#zTQrG6hH[3g\\\\N4lu>e5#KmCj:ZW)9>Fgt^VkCR:6KUNTuEz!,rtI^ABNo_Xt;?gUqe$@Z;9`*dHUo6\\\\c/:@\\'aHZe#!TIJ,K*3%_&ZN_Zk-6N>aZH:/3F(/ib/PJjkS5;9M`u...dstream\\nendobj\\n13 0 obj\\n<<\\n/Filter [ /ASCII85Decode /FlateDecode ] /Length 535\\n>>\\nstream\\nGat=\\'95i<6&AI=/b],qKf/%kNDpVC.W%&r7d6fQ^m&Us[)]E;bqm\"C4]?jH/-F+h@4Q\"&K&S*MqCHhm5Dde\\'FJ->6>W.g!\"$9kiAI=m;MAjJs\\'Zq\"O5@m63&\\'jKXVe?t.c$*0R\\\\9Pr>sdlcJ\\\\S`h&]Y)CBPl)8.Rk`iPGpWdo)0F[,Co-r99RO)C115`N$E6gJAVgJV=`C(ii>B0q$ZK2>R9p6m_0@a4_Qk`QN=r$q/GP-6nfnF!%-b/#o\\\\\\'!XA^#,_Hd!g]BD6`+IP0uMPE!/Q4W7ZFh\"&9Uk=_ll)`63?PAF+$LW&INl<fl[`^\"1^1ThCEBn%pb,f1FenO^[/ZrP2s=dLcr]a9K8TU/FUIoC6tOb4C+Gr`H8T<I`-mGNhp&,hLJH8WnX/V=ReOc(C_[i+:HrD`g[?V1FXNU\"SU*J2!F\\':51LA)IH)>K!0a(i\\\\A1NT1A&22T\"`16(d:N4)Feu5_(&-W=E`nF!U+=BadX+c^8k`Hj_a#?!aGn96a\"sJ-(H&l,:[ub/\"p.^&nSudDu~>endstream\\nendobj\\nxref\\n0 14\\n0000000000 65535 f \\n0000000073 00000 n \\n0000000124 00000 n \\n0000000231 00000 n \\n0000000343 00000 n \\n0000000426 00000 n \\n0000000631 00000 n \\n0000074200 00000 n \\n0000074649 00000 n \\n0000074917 00000 n \\n0000074986 00000 n \\n0000075270 00000 n \\n0000075336 00000 n \\n0000076717 00000 n \\ntrailer\\n<<\\n/ID \\n[<a19b1cbf7a1c4370439b4e3841839780><a19b1cbf7a1c4370439b4e3841839780>]\\n% ReportLab generated PDF document -- digest (http://www.reportlab.com)\\n\\n/Info 10 0 R\\n/Root 9 0 R\\n/Size 14\\n>>\\nstartxref\\n77343\\n%%EOF\\n'\n________________ TestCalibPDF.test_pdf_signature_verification _________________\ntests_smoke\\test_calib_pdf.py:256: in test_pdf_signature_verification\n    assert hash_short in pdf_content, f\"Hash SHA-256 manquant dans le PDF: {hash_short}\"\nE   AssertionError: Hash SHA-256 manquant dans le PDF: e0aa81a413379ce6\nE   assert 'e0aa81a413379ce6' in '%PDF-1.4\\n%\\x93\\x8c\\x8b\\x9e ReportLab Generated PDF document http://www.reportlab.com\\n1 0 obj\\n<<\\n/F1 2 0 R /F2 3 0 R /F3 4 0 R\\n>>\\nendobj\\n2 0 obj\\n<<\\n/BaseFont /Helvetica /Encoding /WinAnsiEncoding /Name /F1 /Subtype /Type1 /Type /Font\\n>>\\nendobj\\n3 0 obj\\n<<\\n/BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding /Name /F2 /Subtype /Type1 /Type /Font\\n>>\\nendobj\\n4 0 obj\\n<<\\n/BaseFont /ZapfDingbats /Name /F3 /Subtype /Type1 /Type /Font\\n>>\\nendobj\\n5 0 obj\\n<<\\n/Contents 12 0 R /MediaBox [ 0 0 595.2756 841.8898 ] /Parent 11 0 R /Resources <<\\n/Font 1 0 R /ProcSet [ /PDF /Text /ImageB /ImageC /ImageI ]\\n>> /Rotate 0 /Trans <<\\n\\n>> \\n  /Type /Page\\n>>\\nendobj\\n6 0 obj\\n<<\\n/BitsPerComponent 8 /ColorSpace /DeviceRGB /Filter [ /ASCII85Decode /FlateDecode ] /Height 817 /Length 73407 /SMask 7 0 R \\n  /Subtype /Image /Type /XObject /Width 1029\\n>>\\nstream\\nGb\",k#C$q_pVoQ*\"f3V9m\"jjQqC,,QWDWn6+WqnW;/\\'M$\\',sP@3X-9B,mbl>6\\'5J?#Q`?[4k.i*8O@aLmekDniag]-h+`&?POndFII_4BgqA(/]XtN5h75t;zzzzzzzzzzzzzzzzzzzzzzzzzMD*/>0-<E-r1AK<WHLc=-7:0Rg9bSDgPCXk[JL\"*zJEGOjAP9\"#V<ZR0F8>B<[JNiUUIUAgF)u-O[V]&GQJ-`fz!5N`)nA,?o$.IcUD\"H)O9@^(EY>V4>iPUG/YZ\\\\<>DV^cX5CWNTLKiE@E?dK1L(,(K-70L\"Q^eXc_3-*;W9\\'qKHE,%j...stream\\nendobj\\n13 0 obj\\n<<\\n/Filter [ /ASCII85Decode /FlateDecode ] /Length 532\\n>>\\nstream\\nGat=\\'9lJN8&A@7.b],qKf/*Eo%9c@7<@($YHK`=>m+%hB6_eII5@_%H0!l<97ognMbkpl;K&hW.mmhp&/Z^T:OJ\\'jK>%hTQi\\'Z8S2g@TB+:-)@p*bk+aIi\"%$<DBrFTkW]_CF^Z;k*I!1ljRo-[JQK1G!*Kc!XhL;QuTV1)R>n&^I<:\\'<ana9>UmB(2Y/XSd23lH3?eSLd7\\'2j9u<*b6uO`L+VC<fBdEda2D;b@pf/:5&WBl\\\\ErA]fDG)=)4\\\\21qt(*HYL(!8EP*Pp\\\\gJDVLo:lM=Kd2#a[.B@RQ&H8q<iop4fo^s\"tF!aal^rc9tekYE^BOSk,_f8FcT#3*9,mt+?Lu7TV3EZ_/<)%;G*/E_s=%^&-\"*T@u4f!o-kX6V*FX:>YDOQ8Hs\\'tk-90RO&H\"NbGr>73*Ub65Y%*d_/h%j(`ak\\\\_\\\\`_!?YT^qYD&q;OoGR1,Pehi@!.d.:\\\\1m:gHI5$TpT2%!h8\\'[M>Lj&j&4SeVVM=2iXBIdf4k\\'o*tg]/5TtV(EH99D#R6adAu*k5~>endstream\\nendobj\\nxref\\n0 14\\n0000000000 65535 f \\n0000000073 00000 n \\n0000000124 00000 n \\n0000000231 00000 n \\n0000000343 00000 n \\n0000000426 00000 n \\n0000000631 00000 n \\n0000074244 00000 n \\n0000074693 00000 n \\n0000074961 00000 n \\n0000075030 00000 n \\n0000075314 00000 n \\n0000075380 00000 n \\n0000076761 00000 n \\ntrailer\\n<<\\n/ID \\n[<93eeb5aca50c6d4119ba5147151b242e><93eeb5aca50c6d4119ba5147151b242e>]\\n% ReportLab generated PDF document -- digest (http://www.reportlab.com)\\n\\n/Info 10 0 R\\n/Root 9 0 R\\n/Size 14\\n>>\\nstartxref\\n77384\\n%%EOF\\n'\n\nDuring handling of the above exception, another exception occurred:\ntests_smoke\\test_calib_pdf.py:261: in test_pdf_signature_verification\n    pytest.fail(f\"Erreur vérification signature: {str(e)}\")\nE   Failed: Erreur vérification signature: Hash SHA-256 manquant dans le PDF: e0aa81a413379ce6\nE   assert 'e0aa81a413379ce6' in '%PDF-1.4\\n%\\x93\\x8c\\x8b\\x9e ReportLab Generated PDF document http://www.reportlab.com\\n1 0 obj\\n<<\\n/F1 2 0 R /F2 3 0 R /F3 4 0 R\\n>>\\nendobj\\n2 0 obj\\n<<\\n/BaseFont /Helvetica /Encoding /WinAnsiEncoding /Name /F1 /Subtype /Type1 /Type /Font\\n>>\\nendobj\\n3 0 obj\\n<<\\n/BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding /Name /F2 /Subtype /Type1 /Type /Font\\n>>\\nendobj\\n4 0 obj\\n<<\\n/BaseFont /ZapfDingbats /Name /F3 /Subtype /Type1 /Type /Font\\n>>\\nendobj\\n5 0 obj\\n<<\\n/Contents 12 0 R /MediaBox [ 0 0 595.2756 841.8898 ] /Parent 11 0 R /Resources <<\\n/Font 1 0 R /ProcSet [ /PDF /Text /ImageB /ImageC /ImageI ]\\n>> /Rotate 0 /Trans <<\\n\\n>> \\n  /Type /Page\\n>>\\nendobj\\n6 0 obj\\n<<\\n/BitsPerComponent 8 /ColorSpace /DeviceRGB /Filter [ /ASCII85Decode /FlateDecode ] /Height 817 /Length 73407 /SMask 7 0 R \\n  /Subtype /Image /Type /XObject /Width 1029\\n>>\\nstream\\nGb\",k#C$q_pVoQ*\"f3V9m\"jjQqC,,QWDWn6+WqnW;/\\'M$\\',sP@3X-9B,mbl>6\\'5J?#Q`?[4k.i*8O@aLmekDniag]-h+`&?POndFII_4BgqA(/]XtN5h75t;zzzzzzzzzzzzzzzzzzzzzzzzzMD*/>0-<E-r1AK<WHLc=-7:0Rg9bSDgPCXk[JL\"*zJEGOjAP9\"#V<ZR0F8>B<[JNiUUIUAgF)u-O[V]&GQJ-`fz!5N`)nA,?o$.IcUD\"H)O9@^(EY>V4>iPUG/YZ\\\\<>DV^cX5CWNTLKiE@E?dK1L(,(K-70L\"Q^eXc_3-*;W9\\'qKHE,%j...stream\\nendobj\\n13 0 obj\\n<<\\n/Filter [ /ASCII85Decode /FlateDecode ] /Length 532\\n>>\\nstream\\nGat=\\'9lJN8&A@7.b],qKf/*Eo%9c@7<@($YHK`=>m+%hB6_eII5@_%H0!l<97ognMbkpl;K&hW.mmhp&/Z^T:OJ\\'jK>%hTQi\\'Z8S2g@TB+:-)@p*bk+aIi\"%$<DBrFTkW]_CF^Z;k*I!1ljRo-[JQK1G!*Kc!XhL;QuTV1)R>n&^I<:\\'<ana9>UmB(2Y/XSd23lH3?eSLd7\\'2j9u<*b6uO`L+VC<fBdEda2D;b@pf/:5&WBl\\\\ErA]fDG)=)4\\\\21qt(*HYL(!8EP*Pp\\\\gJDVLo:lM=Kd2#a[.B@RQ&H8q<iop4fo^s\"tF!aal^rc9tekYE^BOSk,_f8FcT#3*9,mt+?Lu7TV3EZ_/<)%;G*/E_s=%^&-\"*T@u4f!o-kX6V*FX:>YDOQ8Hs\\'tk-90RO&H\"NbGr>73*Ub65Y%*d_/h%j(`ak\\\\_\\\\`_!?YT^qYD&q;OoGR1,Pehi@!.d.:\\\\1m:gHI5$TpT2%!h8\\'[M>Lj&j&4SeVVM=2iXBIdf4k\\'o*tg]/5TtV(EH99D#R6adAu*k5~>endstream\\nendobj\\nxref\\n0 14\\n0000000000 65535 f \\n0000000073 00000 n \\n0000000124 00000 n \\n0000000231 00000 n \\n0000000343 00000 n \\n0000000426 00000 n \\n0000000631 00000 n \\n0000074244 00000 n \\n0000074693 00000 n \\n0000074961 00000 n \\n0000075030 00000 n \\n0000075314 00000 n \\n0000075380 00000 n \\n0000076761 00000 n \\ntrailer\\n<<\\n/ID \\n[<93eeb5aca50c6d4119ba5147151b242e><93eeb5aca50c6d4119ba5147151b242e>]\\n% ReportLab generated PDF document -- digest (http://www.reportlab.com)\\n\\n/Info 10 0 R\\n/Root 9 0 R\\n/Size 14\\n>>\\nstartxref\\n77384\\n%%EOF\\n'\n____________________ TestCalibPDF.test_pdf_error_handling _____________________\ntests_smoke\\test_calib_pdf.py:271: in test_pdf_error_handling\n    with pytest.raises(Exception):\nE   Failed: DID NOT RAISE <class 'Exception'>\n-------------------------- Captured stdout teardown ---------------------------\n\n=== Nettoyage environnement de test ===\n=========================== short test summary info ===========================\nFAILED tests_smoke/test_calib_pdf.py::TestCalibPDF::test_pdf_content_verification\nFAILED tests_smoke/test_calib_pdf.py::TestCalibPDF::test_pdf_signature_verification\nFAILED tests_smoke/test_calib_pdf.py::TestCalibPDF::test_pdf_error_handling\n========================= 3 failed, 3 passed in 4.88s =========================\n",
      "error": ""
    }
  }
}